import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import Image from '@11ty/eleventy-img';
import sharp from 'sharp';

export const imageCache = '.cache/images';
const prefix = (process.env.PATH_PREFIX || '').replace(/^\/$/, '').replace(/\/$/, '');
const imageOptions = {
  formats: ['avif', 'webp'],
  outputDir: imageCache,
  urlPath: `${prefix}/img`,
  sharpWebpOptions: { quality: 90 },
  sharpAvifOptions: { quality: 75 },
};

const escape = value => String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const srcset = entries => entries.map(image => `${image.url} ${image.width}w`).join(', ');

export async function imageMetadata(src, widths = [640, 1280, 1920]) {
  try {
    return await Image(src, { ...imageOptions, widths });
  } catch (cause) {
    throw new Error(`Cannot process image ${src}: ${cause.message}`, { cause });
  }
}

export async function stripImage(src) {
  const metadata = await imageMetadata(src, [320, 640, 1280, 1920]);
  const wall = await Promise.all([1, 2].map(async density => {
    const crop = await sharp(src).rotate().resize(160 * density, 1000 * density, { fit: 'cover' }).png().toBuffer();
    const encoded = await Image(crop, { ...imageOptions, widths: [160 * density] });
    return { density, encoded };
  }));
  return {
    src: metadata.webp[0].url,
    avif: srcset(metadata.avif),
    webp: srcset(metadata.webp),
    width: metadata.webp[0].width,
    height: metadata.webp[0].height,
    wallAvif: wall.map(({ density, encoded }) => `${encoded.avif[0].url} ${density}x`).join(', '),
    wallWebp: wall.map(({ density, encoded }) => `${encoded.webp[0].url} ${density}x`).join(', '),
  };
}

export async function responsiveImage(src, alt = '', className = 'media-img', sizes = '(max-width: 768px) calc(100vw - 48px), calc(100vw - 112px)', mobileSrc = null) {
  const metadata = await imageMetadata(src);
  const lcp = className.split(' ').includes('lcp');
  const fallback = metadata.webp.at(-1);
  let sources = '';
  if (mobileSrc) {
    const mobile = await imageMetadata(mobileSrc);
    for (const format of ['avif', 'webp']) {
      const first = mobile[format][0];
      sources += `<source media="(max-width: 768px)" type="image/${format}" srcset="${escape(srcset(mobile[format]))}" sizes="${escape(sizes)}" width="${first.width}" height="${first.height}">`;
    }
  }
  for (const format of ['avif', 'webp']) {
    sources += `<source type="image/${format}" srcset="${escape(srcset(metadata[format]))}" sizes="${escape(sizes)}">`;
  }
  return `<picture>${sources}<img src="${fallback.url}" alt="${escape(alt)}" class="${escape(className)}" width="${fallback.width}" height="${fallback.height}" loading="${lcp ? 'eager' : 'lazy'}" decoding="async"${lcp ? ' fetchpriority="high"' : ''}></picture>`;
}

export function ogFingerprint(src) {
  return createHash('sha256').update(readFileSync(src)).update('og-1200x630-attention-q82-v1').digest('hex').slice(0, 12);
}

export async function ogImage(src, slug) {
  const filename = `og/${slug}-${ogFingerprint(src)}.jpg`;
  const output = path.join(imageCache, filename);
  if (!existsSync(output)) {
    mkdirSync(path.dirname(output), { recursive: true });
    await sharp(src).resize(1200, 630, { fit: 'cover', position: sharp.strategy.attention }).jpeg({ quality: 82, mozjpeg: true }).toFile(output);
  }
  return `${prefix}/img/${filename}`;
}

export function* walkFiles(directory) {
  if (!existsSync(directory)) return;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) yield* walkFiles(filename);
    else yield filename;
  }
}

// Cache files stay outside the deployment. Only URLs used by the rendered site
// are copied, including srcsets and the higher-resolution hover candidates.
export function publishImages(outputDir = 'dist') {
  const referenced = new Set();
  for (const filename of walkFiles(outputDir)) {
    if (!/\.(html|css|js|xml)$/.test(filename)) continue;
    for (const match of readFileSync(filename, 'utf8').matchAll(/\/img\/([a-zA-Z0-9_./-]+\.(?:avif|webp|jpg|png))/g)) {
      const relative = match[1];
      if (relative.includes('..')) throw new Error(`Invalid image path in ${filename}: ${relative}`);
      // /assets/img is passed through separately, not generated by this pipeline.
      if (!existsSync(path.join(imageCache, relative))) {
        if (existsSync(path.join(outputDir, 'assets/img', relative))) continue;
        throw new Error(`Missing generated image ${relative}, referenced by ${filename}`);
      }
      referenced.add(relative);
    }
  }
  for (const relative of referenced) {
    const output = path.join(outputDir, 'img', relative);
    mkdirSync(path.dirname(output), { recursive: true });
    copyFileSync(path.join(imageCache, relative), output);
  }
  writeFileSync(path.join(outputDir, 'image-manifest.json'), JSON.stringify([...referenced].sort().map(filename => `${prefix}/img/${filename}`), null, 2) + '\n');
}
